public enum ApplicationType
{
    None,

    EmailOffer = 1,
    EmailProforma = 2,
    EmailPoaPneu = 7,
    EmailAcceptPayment = 8,
    EmailSalesCZ = 9,
    EmailSalesCZWithFinance = 10,
    EmailSalesToEU = 11,
    EmailSalesOutEU = 12,
    EmailRequestForEK = 13,
    EmailRequestForSTK = 14,
    EmailReqForSales = 15,
    EmailReqForSalesOutCZ = 16,
    EmailExpressReq = 17,
    EmailVATReturn = 18,
    EmailVehiclePaid = 19,
    EmailInspectReport = 23,
    EmailBuyReq = 24,
    EmailVehicleOnBoard = 25,
    EmailVehicleOnClient = 26,
    EmailProformaEPH = 27,
    EmailProformaPRE = 28,
    EmailProformaEU = 29,
    EmailProformaCrashODP = 30,
    EmailProformaCrashService = 31,
    EmailPoaTakeImmobileVehicle = 32,
    EmailPoaTakeWithCodes = 33,
    EmailPoaPneuDS = 34,
    EmailSaleWholesaler = 35,
    EmailTransferProtocol = 36,
    EmailProformaOutEU = 37,
    EmailConfirmationOfArrival = 38,
    EmailCallForDigitalSignEPH = 39,

    EmailPreparationOrders = 100,

    NotificationAuctionRequested = 500,
    NotificationLoss = 501,
    NotificationLossApproved = 502,
    NotificationLossExcessive = 503,
    NotificationPrematureB2B = 504,
    NotificationPrematureB2C = 505,
    NotificationLossToB2B = 506,
    NotificationLossToB2C = 507,
    NotificationAuctionApproved = 508,
    NotificationDirectSale = 509,
    NotificationOfferToBuyVehicle = 510,
    NotificationReminder1 = 511,
    NotificationReminder2 = 512,

    LogCc3RequestCreated = 600,

    NotificationInspectionReport = 550,
    NotificationPreinspectionReport = 551,
    NotificationInspectionCreated = 552,
    NotificationInspectionRejected = 553,
    NotificationInspectionCanceled = 554,

    Documents = 1000,
    DocumentProformaOutEU = 1001,
    DocumentOrderConfirmation = 1004,
    DocumentPoaPneu = 1006,
    DocumentPurchaseContractB2C = 1007,
    DocumentProformaWithFinance = 1008,
    DocumentRequestForEK = 1011,
    DocumentRequestForSTK = 1012,
    DocumentPoaSPZService = 1013,
    DocumentReqForExportLicensePlate = 1014,
    DocumentPoaPneuMakrofakt = 1015,
    DocumentPurchaseContractOutODP = 1018,
    DocumentInstructionToBuy = 1020,
    DocumentPurchaseContractODP = 1021,
    DocumentProformaPRE = 1022,
    DocumentProformaCZ = 1023,
    DocumentProformaEU = 1024,
    DocumentTransferProtocol = 1025,
    DocumentHandoverProtocol = 1026,

    ResponseError = 2000,
    ResponseInspectionCanceled = 2001,
}